apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ .cloneVolumeSnapshotName }}-{{ sub .Replica 1 }}
spec:
  volumeSnapshotClassName: {{ .volumeSnapshotClassName }}
  source:
    persistentVolumeClaimName: {{ .cloneVolumeSnapshotPVCName }}-{{ sub .Replica 1 }}
