apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: {{ .name }}
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  source:
    pvc:
      namespace: {{ .sourceNamespace }}
      name: {{ .sourcePVCName }}
  storage:
    accessModes:
    - {{ .accessMode }}
    resources:
      requests:
        storage: {{ .storage }}
    storageClassName: {{ .storageClass }}
