apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: "{{ .name }}-{{ .Replica }}"
spec:
  dataVolumeTemplates:
  - metadata:
      name: "{{ .name }}-{{ .Replica }}-root"
    spec:
      sourceRef:
        kind: DataSource
        name: {{ .dataSourceName }}
        namespace: {{ .Namespace }}
      storage:
        accessModes:
        - {{ .accessMode }}
        storageClassName: {{ .storageClassName }}
        resources:
          requests:
            storage: {{ .dataVolumeSize }}
  {{ range $dataVolumeIndex := .dataVolumeCounters }}
  - metadata:
      name: "{{ $.name }}-{{ $.Replica }}-data-{{ $dataVolumeIndex }}"
    spec:
      source:
        blank: {}
      storage:
        accessModes:
        - {{ $.accessMode }}
        storageClassName: {{ $.storageClassName }}
        resources:
          requests:
            storage: {{ $.dataVolumeSizeAdditional }}
  {{ end }}
  runStrategy: RerunOnFailure
  template:
    spec:
      accessCredentials:
      - sshPublicKey:
          propagationMethod:
            noCloud: {}
          source:
            secret:
              secretName: {{ .sshPublicKeySecret }}
      architecture: amd64
      domain:
        cpu:
          cores: {{ .cpuCores }}
        resources:
          requests:
            memory: {{ .memory }}
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
            bootOrder: 1
          {{ range $dataVolumeIndex := .dataVolumeCounters }}
          - disk:
              bus: virtio
            name: "data-{{ $dataVolumeIndex }}"
          {{ end }}
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - name: default
            masquerade: {}
            bootOrder: 2
        machine:
          type: pc-q35-rhel9.4.0
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: "{{ .name }}-{{ .Replica }}-root"
        name: rootdisk
      {{ range $dataVolumeIndex := .dataVolumeCounters }}
      - dataVolume:
          name: "{{ $.name }}-{{ $.Replica }}-data-{{ $dataVolumeIndex }}"
        name: "data-{{ $dataVolumeIndex }}"
      {{ end }}
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            chpasswd:
              expire: false
            password: fedora
            user: fedora
        name: cloudinitdisk
